version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: cryptocrew-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cryptocrew-app
    ports:
      - "3000:3000"
      - "8001:8001"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      - chromadb
    restart: unless-stopped

volumes:
  chroma_data:
